version: v1.0.0

baseDemoContainer: &baseDemoContainer
  name: demo
  image: debian:stretch

jobs:

  foo:
    containers:
    - <<: *baseDemoContainer
      command: echo foo

  bar:
    containers:
    - <<: *baseDemoContainer
      command: echo bar

pipelines:

  ci:
    triggers:
    - spec:
        uri: github.com/lovethedrake/drakespec-github
        version: v1.0.0
      config:
        checkSuiteRequest:
          branches:
            only:
            - /.*/
    jobs:
    - name: foo
    - name: bar
      dependencies:
      - foo
