specUri: github.com/lovethedrake/drakespec
specVersion: v0.4.0

jobs:

  foo:
    primaryContainer:
      name: demo
      image: debian:stretch
      command: ["echo"]
      args: ["foo"]

  bar:
    primaryContainer:
      name: demo
      image: debian:stretch
      command: ["echo"]
      args: ["bar"]

  fail:
    primaryContainer:
      name: demo
      image: debian:stretch
      command: ["false"]

pipelines:

  ci:
    triggers:
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
        push:
          branches:
            only:
            - /.*/
    jobs:
    - name: foo
    - name: bar
      dependencies:
      - foo
